# Generated by Django 5.1.7 on 2025-04-07 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "price_usd",
                    models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
                ),
                ("market_cap", models.BigIntegerField(default=0)),
                ("volume_24h", models.BigIntegerField(default=0)),
                ("percent_change_24h", models.FloatField(default=0.0)),
                ("circulating_supply", models.BigIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConversionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_currency", models.CharField(max_length=10)),
                ("to_currency", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "converted_amount",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
